import AppKit
import CryptoKit

/// Polls the general pasteboard (the standard approach on macOS; there is no change notification).
final class Monitor {
    var paused = false
    var onCapture: (Capture) -> Void = { _ in }

    private let pb = NSPasteboard.general
    private var lastChange: Int
    private var ownChange: Int?
    private var timer: Timer?

    /// Text larger than this is not recorded.
    private let maxTextLength = 2_000_000

    /// Rich representations kept alongside the plain text, so items can be pasted with formatting.
    private let richTypes: [NSPasteboard.PasteboardType] = [
        .rtf, .html, NSPasteboard.PasteboardType("com.apple.flat-rtfd"),
    ]
    private let maxFormatBytes = 10_000_000

    init() { lastChange = NSPasteboard.general.changeCount }

    func start() {
        timer = Timer.scheduledTimer(withTimeInterval: 0.4, repeats: true) { [weak self] _ in self?.check() }
        timer?.tolerance = 0.1
    }

    /// Ignore the next change because Shelf itself wrote it.
    func markOwnChange() { ownChange = pb.changeCount }

    private func check() {
        let count = pb.changeCount
        guard count != lastChange else { return }
        lastChange = count
        guard !paused, count != ownChange else { return }

        let types = Set(pb.types ?? [])
        // Apps mark throwaway pasteboard contents with these (nspasteboard.org convention).
        if types.contains(NSPasteboard.PasteboardType("org.nspasteboard.TransientType")) ||
            types.contains(NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")) { return }

        let app = NSWorkspace.shared.frontmostApplication
        guard var capture = read(types) else { return }
        capture.sourceBundle = app?.bundleIdentifier
        capture.sourceName = app?.localizedName
        onCapture(capture)
    }

    private func read(_ types: Set<NSPasteboard.PasteboardType>) -> Capture? {
        if types.contains(.fileURL),
           let urls = pb.readObjects(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]) as? [URL],
           !urls.isEmpty {
            let paths = urls.map(\.path).joined(separator: "\n")
            return Capture(kind: .file, text: paths, detail: urls.count == 1 ? "1 file" : "\(urls.count) files",
                           hash: Self.digest("file", Data(paths.utf8)))
        }

        if let s = pb.string(forType: .string) ?? richPlainText(), !s.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            guard s.count <= maxTextLength else { return nil }
            let kind: ClipKind = Self.isLink(s) ? .link : .text
            let formats = richTypes.compactMap { type -> (type: String, data: Data)? in
                guard types.contains(type), let data = pb.data(forType: type), data.count <= maxFormatBytes else { return nil }
                return (type.rawValue, data)
            }
            return Capture(kind: kind, text: s, hash: Self.digest("text", Data(s.utf8)), formats: formats)
        }

        if types.contains(.png) || types.contains(.tiff) {
            guard let raw = pb.data(forType: .png) ?? pb.data(forType: .tiff),
                  let rep = NSBitmapImageRep(data: raw) else { return nil }
            let png = types.contains(.png) ? raw : (rep.representation(using: .png, properties: [:]) ?? raw)
            return Capture(kind: .image, imageData: png, detail: "\(rep.pixelsWide) × \(rep.pixelsHigh)",
                           hash: Self.digest("image", png))
        }
        return nil
    }

    /// Plain text for apps that put only RTF/HTML on the pasteboard.
    private func richPlainText() -> String? {
        if let rtf = pb.data(forType: .rtf) { return NSAttributedString(rtf: rtf, documentAttributes: nil)?.string }
        if let html = pb.data(forType: .html) { return NSAttributedString(html: html, documentAttributes: nil)?.string }
        return nil
    }

    static func isLink(_ s: String) -> Bool {
        let t = s.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !t.contains(where: \.isWhitespace), let url = URL(string: t),
              let scheme = url.scheme?.lowercased(), ["http", "https"].contains(scheme), url.host != nil
        else { return false }
        return true
    }

    static func digest(_ kind: String, _ data: Data) -> String {
        var h = SHA256()
        h.update(data: Data(kind.utf8))
        h.update(data: data)
        return h.finalize().map { String(format: "%02x", $0) }.joined()
    }
}
